In [1]:
import pandas as pd
import mysql.connector

from sqlalchemy import create_engine

In [2]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Batool1234@",
    database="sakila",
    port=3306
)

print("Connected Successfully")

Connected Successfully

In [19]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Batool1234%40@127.0.0.1:3306/dw_movie"
)

print("Engine Created Successfully")

Engine Created Successfully

In [10]:
df_rental = pd.read_sql(
    "SELECT * FROM rental",
    conn
)

df_customer = pd.read_sql(
    "SELECT * FROM customer",
    conn
)

df_film = pd.read_sql(
    "SELECT * FROM film",
    conn
)

df_payment = pd.read_sql(
    "SELECT * FROM payment",
    conn
)

df_inventory = pd.read_sql(
    "SELECT * FROM inventory",
    conn
)

print("Data Extracted Successfully")

C:\Users\USER-Q\AppData\Local\Temp\ipykernel_9048\1802258354.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_rental = pd.read_sql(
C:\Users\USER-Q\AppData\Local\Temp\ipykernel_9048\1802258354.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_customer = pd.read_sql(
C:\Users\USER-Q\AppData\Local\Temp\ipykernel_9048\1802258354.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_film = pd.read_sql(
C:\Users\USER-Q\AppData\Local\Temp\ipykernel_9048\1802258354.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_payment = pd.read_sql(

Data Extracted Successfully

C:\Users\USER-Q\AppData\Local\Temp\ipykernel_9048\1802258354.py:21: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_inventory = pd.read_sql(

In [11]:
df_rental["rental_duration"] = (
    pd.to_datetime(df_rental["return_date"]) -
    pd.to_datetime(df_rental["rental_date"])
).dt.days


# Create Full Name

df_customer["full_name"] = (
    df_customer["first_name"] + " " +
    df_customer["last_name"]
)


# Convert Dates

df_rental["rental_date"] = pd.to_datetime(
    df_rental["rental_date"]
)

df_payment["payment_date"] = pd.to_datetime(
    df_payment["payment_date"]
)

print("Transformation Completed")

Transformation Completed

In [12]:
print(df_rental.isnull().sum())

rental_id            0
rental_date          0
inventory_id         0
customer_id          0
return_date        183
staff_id             0
last_update          0
rental_duration    183
dtype: int64

In [13]:
dim_customer = df_customer[[
    "customer_id",
    "full_name",
    "email",
    "active",
    "store_id"
]]

dim_customer.head()

,customer_id,full_name,email,active,store_id
0,1,MARY SMITH,MARY.SMITH@sakilacustomer.org,1,1
1,2,PATRICIA JOHNSON,PATRICIA.JOHNSON@sakilacustomer.org,1,1
2,3,LINDA WILLIAMS,LINDA.WILLIAMS@sakilacustomer.org,1,1
3,4,BARBARA JONES,BARBARA.JONES@sakilacustomer.org,1,2
4,5,ELIZABETH BROWN,ELIZABETH.BROWN@sakilacustomer.org,1,1

In [20]:
dim_customer.to_sql(
    name="dim_customer",
    con=engine,
    if_exists="replace",
    index=False
)

print("dim_customer Loaded Successfully")

dim_customer Loaded Successfully

In [21]:
dim_film = df_film[[
    "film_id",
    "title",
    "release_year",
    "rental_rate",
    "rating"
]]

dim_film.head()

   film_id             title  release_year  rental_rate rating
0        1  ACADEMY DINOSAUR          2006         0.99     PG
1        2    ACE GOLDFINGER          2006         4.99      G
2        3  ADAPTATION HOLES          2006         2.99  NC-17
3        4  AFFAIR PREJUDICE          2006         2.99      G
4        5       AFRICAN EGG          2006         2.99      G

In [22]:
dim_film.to_sql(
    name="dim_film",
    con=engine,
    if_exists="replace",
    index=False
)

print("dim_film Loaded Successfully")

dim_film Loaded Successfully

In [23]:
dim_date = pd.DataFrame()

dim_date["date"] = df_rental["rental_date"].dt.date
dim_date["year"] = df_rental["rental_date"].dt.year
dim_date["month"] = df_rental["rental_date"].dt.month
dim_date["day"] = df_rental["rental_date"].dt.day

dim_date = dim_date.drop_duplicates()

dim_date.head()

           date  year  month  day
0    2005-05-24  2005      5   24
8    2005-05-25  2005      5   25
145  2005-05-26  2005      5   26
319  2005-05-27  2005      5   27
485  2005-05-28  2005      5   28

In [24]:
dim_date.to_sql(
    name="dim_date",
    con=engine,
    if_exists="replace",
    index=False
)

print("dim_date Loaded Successfully")

dim_date Loaded Successfully

In [25]:
fact_rental = df_rental[[
    "rental_id",
    "rental_date",
    "inventory_id",
    "customer_id",
    "return_date",
    "staff_id",
    "rental_duration"
]]

fact_rental.head()

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,rental_duration
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,1.0
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,3.0
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,7.0
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,9.0
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,8.0

In [26]:
fact_rental.to_sql(
    name="fact_rental",
    con=engine,
    if_exists="replace",
    index=False
)

print("fact_rental Loaded Successfully")

fact_rental Loaded Successfully

In [27]:
fact_payment = df_payment[[
    "payment_id",
    "customer_id",
    "staff_id",
    "rental_id",
    "amount",
    "payment_date"
]]

fact_payment.head()

   payment_id  customer_id  staff_id  rental_id  amount        payment_date
0           1            1         1         76    2.99 2005-05-25 11:30:37
1           2            1         1        573    0.99 2005-05-28 10:35:23
2           3            1         1       1185    5.99 2005-06-15 00:54:12
3           4            1         2       1422    0.99 2005-06-15 18:02:53
4           5            1         2       1476    9.99 2005-06-15 21:08:46

In [28]:
fact_payment.to_sql(
    name="fact_payment",
    con=engine,
    if_exists="replace",
    index=False
)

print("fact_payment Loaded Successfully")

fact_payment Loaded Successfully

In [29]:
fact_inventory = df_inventory[[
    "inventory_id",
    "film_id",
    "store_id"
]]

fact_inventory.head()

   inventory_id  film_id  store_id
0             1        1         1
1             2        1         1
2             3        1         1
3             4        1         1
4             5        1         2

In [31]:
fact_inventory.to_sql(
    name="fact_inventory",
    con=engine,
    if_exists="replace",
    index=False
)

print("fact_inventory Loaded Successfully")

fact_inventory Loaded Successfully

In [32]:
print(fact_rental.shape)
print(fact_payment.shape)
print(fact_inventory.shape)

(16044, 7)
(16044, 6)
(4581, 3)

In [33]:
top_films = fact_rental.merge(
    df_inventory,
    on="inventory_id"
).merge(
    df_film,
    on="film_id"
)

top_films = top_films.groupby(
    "title"
).size().reset_index(
    name="rental_count"
)

top_films.sort_values(
    "rental_count",
    ascending=False
).head(10)

                   title  rental_count
96    BUCKET BROTHERHOOD            34
705     ROCKETEER MOTHER            33
733        SCALAWAG DUCK            32
697  RIDGEMONT SUBMARINE            32
361       GRIT CLOCKWORK            32
312       FORWARD TEMPLE            32
465       JUGGLER HARDLY            32
29         APACHE DIVINE            31
719      RUSH GOODFELLAS            31
930            WIFE TURN            31

In [34]:
top_customers = fact_rental.merge(
    dim_customer,
    on="customer_id"
)

top_customers = top_customers.groupby(
    "full_name"
).size().reset_index(
    name="rental_count"
)

top_customers.sort_values(
    "rental_count",
    ascending=False
).head(10)

          full_name  rental_count
175    ELEANOR HUNT            46
318       KARL SEAL            45
379     MARCIA DEAN            42
105      CLARA SHAW            42
536   TAMMY SANDERS            41
590     WESLEY BULL            40
531      SUE PETERS            40
551        TIM CARY            39
389   MARION SNYDER            39
474  RHONDA KENNEDY            39

In [35]:
monthly_rentals = fact_rental.groupby(
    fact_rental["rental_date"].dt.to_period("M")
).size().reset_index(
    name="rental_count"
)

monthly_rentals["rental_date"] = (
    monthly_rentals["rental_date"].astype(str)
)

monthly_rentals.head()

  rental_date  rental_count
0     2005-05          1156
1     2005-06          2311
2     2005-07          6709
3     2005-08          5686
4     2006-02           182

In [36]:
revenue_customers = fact_payment.merge(
    dim_customer,
    on="customer_id"
)

revenue_customers = revenue_customers.groupby(
    "full_name"
)["amount"].sum().reset_index()

revenue_customers.sort_values(
    "amount",
    ascending=False
).head(10)

          full_name  amount
318       KARL SEAL  221.55
175    ELEANOR HUNT  216.54
105      CLARA SHAW  195.58
389   MARION SNYDER  194.61
474  RHONDA KENNEDY  194.61
556   TOMMY COLLAZO  186.62
590     WESLEY BULL  177.60
551        TIM CARY  175.61
379     MARCIA DEAN  175.58
21      ANA BRADLEY  174.66

In [37]:
monthly_revenue = fact_payment.groupby(
    fact_payment["payment_date"].dt.to_period("M")
)["amount"].sum().reset_index()

monthly_revenue.head()

  payment_date    amount
0      2005-05   4823.44
1      2005-06   9629.89
2      2005-07  28368.91
3      2005-08  24070.14
4      2006-02    514.18

In [38]:
staff_performance = fact_payment.groupby(
    "staff_id"
)["amount"].sum().reset_index()

staff_performance.sort_values(
    "amount",
    ascending=False
).head()

   staff_id    amount
1         2  33924.06
0         1  33482.50

In [39]:
film_stock = fact_inventory.merge(
    dim_film,
    on="film_id"
)

film_stock.groupby(
    "title"
).size().reset_index(
    name="copies"
).sort_values(
    "copies",
    ascending=False
).head(10)

                     title  copies
381            HARRY IDAHO       8
730         SATURDAY LAMBS       8
733          SCALAWAG DUCK       8
191          DANCING FEVER       8
957              ZORRO ARK       8
0         ACADEMY DINOSAUR       8
560  MOCKINGBIRD HOLLYWOOD       8
813        STORM HAPPINESS       8
357         GREATEST NORTH       8
872            TRIP NEWTON       8

In [40]:
fact_inventory.groupby(
    "store_id"
).size().reset_index(
    name="inventory_count"
)

   store_id  inventory_count
0         1             2270
1         2             2311

In [41]:
fact_inventory.groupby(
    "film_id"
).size().reset_index(
    name="inventory_distribution"
).head(10)

   film_id  inventory_distribution
0        1                       8
1        2                       3
2        3                       4
3        4                       7
4        5                       3
5        6                       6
6        7                       5
7        8                       4
8        9                       5
9       10                       7

In [42]:
conn.close()

print("Connection Closed")

Connection Closed